pipeline {
    agent any

    environment {
        ACR_REGISTRY = 'acrghassendev.azurecr.io'
        IMAGE_NAME   = 'frontend'
        IMAGE_TAG    = "${ACR_REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}"
        IMAGE_LATEST = "${ACR_REGISTRY}/${IMAGE_NAME}:latest"
    }

    stages {
        stage('1. Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('2. Secret Scan') {
            steps {
                dir('InsomeaTech_Dev_Frontend') {
                    sh 'docker run --rm -v $(pwd):/path zricethezav/gitleaks:latest detect --source="/path" --no-git --verbose || true'
                }
            }
        }

        stage('3. Build Angular Container') {
            steps {
                dir('InsomeaTech_Dev_Frontend') {
                    sh "docker build --no-cache -t ${IMAGE_TAG} -t ${IMAGE_LATEST} ."
                }
            }
        }

        stage('4. Trivy Vulnerability Gate') {
            steps {
                dir('InsomeaTech_Dev_Frontend') {
                    sh '''
                        cat << 'EOF' > .trivyignore
                        CVE-2026-14257
                        CVE-2026-69152
                        EOF

                        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/workspace aquasec/trivy:latest image --severity HIGH,CRITICAL --ignore-unfixed --ignorefile /workspace/.trivyignore --exit-code 1 ${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('5. Push to ACR') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'acrghassendev', usernameVariable: 'ACR_USER', passwordVariable: 'ACR_PASS')]) {
                    sh '''
                        echo "$ACR_PASS" | docker login $ACR_REGISTRY -u "$ACR_USER" --password-stdin
                        docker push $IMAGE_TAG
                        docker push $IMAGE_LATEST
                    '''
                }
            }
        }
    }
	stage('6. Trigger Azure App Service Update') {
            steps {
                sh 'az webapp restart --name app-insomea-frontend-dev --resource-group rg-GhassenHafsawi'
            }
        }
    post {
        always {
            sh "docker logout $ACR_REGISTRY || true"
            cleanWs()
        }
    }
}
